services:
  # Backend API Service
  - type: web
    name: fsoc-backend
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python train_models.py --train"
    startCommand: "python backend_main.py"
    healthCheckPath: "/health"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"

  # Frontend Web Service
  - type: web
    name: fsoc-frontend
    env: python
    plan: free
    buildCommand: "pip install flask gunicorn requests"
    startCommand: "python frontend_main.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: BACKEND_API_URL
        value: https://fsoc-backend.onrender.com  # Update this with your actual backend URL
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
